### ISSUE TITLE
[feat] 배포를 한다.

### ISSUE THREAD

**Issue by ghrltjdtprbs** [10aeat/10aeat_Backend#20]
# 목적
- 코드가 수정될 때마다 개발자가 배포에 신경을 덜 쓸 수 있도록 CI/CD를 구축합니다

# 구성 요소
**DockerFile :**
0. 멀티 스테이징을 활용해 빌드시에만 필요한 파일들을 배포 이미지에 포함되지 않도록 경량화 과정을 거칩니다
  - 스테이징은 FROM 키워드에서 구분됩니다

1. 빌드 단계
```dockerfile
FROM openjdk:17-jdk-slim AS build
WORKDIR /app
COPY . .
#RUN ./gradlew test
RUN ./gradlew bootJar
```

  -  **FROM :** openjdk-17 slim버전을 사용하여 빌드 환경 지정
  - **AS : ** 이 과정에서 작성된 파일들을 build라는 이름으로 사용 할 수 있도록 지정
  - **WORKDIR :** 명령어를 실행할 디렉토리 지정 -> cd 명령어와 비슷함
  - **COPY :** 프로젝트의 모든 파일을 컨테이너의 작업 디렉토리로 복사
  - **RUN :** 컨테이너 내부에서 명령어 실행
    - 내부에서 yes 등 별도의 명령어를 받아야 하는 경우 오류로 간주되어 빌드 종료
    - **./gradlew test :** gradlew에서 테스트 코드를 실행하는 명령어, 현재 주석처리됨
    - **./gradlew bootJar: ** gradlew에서 bootJar 실행

2. 경량화 단계
```dockerfile
FROM amazoncorretto:17-alpine as corretto-jdk
# required for strip-debug to work
RUN apk add --no-cache binutils
# Build small JRE image
RUN jlink \
      --verbose \
      --add-modules java.base,java.compiler,java.desktop,java.instrument,java.management,java.naming,java.prefs,java.rmi,java.scripting,java.security.jgss,java.sql,jdk.httpserver,jdk.jfr,jdk.unsupported,jdk.crypto.ec,jdk.crypto.cryptoki \
      --strip-debug \
      --no-man-pages \
      --no-header-files \
      --compress=2 \
      --output /jre
```
  - **binutils :**  JRE(Java Runtime Envirment)을 만들 때 strip-dubug 옵션을 위해 사용(디버그 정보 제거 옵션)
  - **--no-cache :** 패키지 설치 시 캐시 사용 안함
  - **jlink :** java의 빌드 도구중 하나, 사용하는 모듈만으로 java 환경을 만들 수 있음
    - -**--add-modules: ** 포함할 모듈 지정 - 현재는 필요하지 않은 모듈들도 일부 포함되어 있는 상태입니다!
    - **--no-man-pages: ** 메뉴얼 페이지를 포함하지 않음
    - **--no-header-files: ** 헤더파일 포함 하지 않음
    - **--compress=2** 압축 레벨 설정 0 ~ 2까지 설정 가능, 0 = 압축하지 않음
    - **--output** 생성된 파일을 출력할 경로
3. 실행 단계
```dockerfile
# ### 실행 단계
FROM alpine:latest
ENV JAVA_HOME=/jre
ENV PATH="${JAVA_HOME}/bin:${PATH}"
COPY --from=corretto-jdk /jre $JAVA_HOME
# 환경 변수 설정
ENV SPRING_PROFILES_ACTIVE=develop
# ENV로 실제 애플리케이션에서 사용할 환경변수 설정
ENV DATABASE_URL=""
ENV DATABASE_PASSWORD=""
ARG JAR_FILE=/app/build/libs/*.jar
COPY --from=build /app/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
```
   - **ENV :** 환경변수 설정 도커 실행시 -e 환경변수 이름=값 으로 주입 가능
   - **ENTRYPOINT :** 컨테이너 시작시 항상 실행될 명령어, []내부에서 , 로 띄어쓰기를 구분하여 실행함

**ci-cd.yml :**
1. **on.push.branches :** develop 브랜치에 push 될 때 실행되도록 설정,
2. **jobs.build.runs-on: ** ubuntu-22.04 환경에서 실행됨을 명시
3. **actions/checkout@v3 :** 워크플로우에서 저장소에 접근 할 수 있도록 함
4. **Gradle 캐싱 처리 :** 빌드 시간과 통신을 줄이기 위해 의존성 패키지를 캐싱해서 사용
5. 자바 버전 설정
6. **Grant execute permission for gradlew :** Gradlew에 실행 권한을 부여
7. **Build and Test with Gradle :** 프로젝트 빌드 
  - --parallel : Gradle 빌드 병렬 실행 옵션
  - -x test : 테스트 실행하지 않음 옵션
8. **Extract metadata (tags, labels) for Docker :** Docker 이미지에 사용할 태그와 라벨을 추출 
9. **ssh to ec2 and run docker :** ssh를 실행
  - appleboy/ssh-action@master: ssh를 사용할 의존성
  - docker stop my-container : 기존에 실행되는 my-container 를 종료
  - docker rm my-container : my-container 삭제 - 삭제하지 않는경우 이름 중복 문제 발생
  - docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:develop : 도커 이미지를 pull 하는 명령어
  - docker run .... : docker를 실행하는 명령어
    - --name : 컨테이너의 이름을 지정 - 추후 ssh로 정적으로 핸들링 할 수 있도록 이름을 my-container로 설정
    - -e  :컨테이너에 주입할 환경변수
    - - p 호스트Port:컨테이너Port : 호스트의 포트와 컨테이너의 포트를 매핑
    - -d : 백그라운드에서 실행 옵션
#### 이슈
#31 
#34
#### Reference
- [Spring Boot 컨테이너 이미지 사이즈 경량화 방법](https://www.sktenterprise.com/bizInsight/blogDetail/dev/7371)
- [Oracle JLink 공식 문서](https://docs.oracle.com/en/java/javase/11/tools/jlink.html)
- [GitActions Checkout](https://github.com/marketplace/actions/checkout)
- [Github Actions에서 Gradle 캐싱하기](https://devjem.tistory.com/76)

**Comment by Galmaeki** [comment]
문서 작성 완료했습니다!
확인하시고 보완할 점 있으시면 말씀해주세요!

**Comment by asd42270** [comment]
고생하셨습니다!!!
