### ISSUE TITLE
[feat] Security 설정을 한다.

### ISSUE THREAD

**Issue by asd42270** [10aeat/10aeat_Backend#22]
# 목적 및 배경
## 목적
기획 전 Spring Security에 대한 설정을 진행하여 개발 기간 단축을 기대합니다

## 배경
- FE와의 회의에서 채택한 Token 방식을 사용하여 로그인 기능을 이용하며, Response Header 삽입 방식을 채택합니다
- 비밀번호 암호화 방식으로 일반적으로 많이 사용되는 BCryptPasswordEncoder를 기본으로 설정합니다
- 개발 진행 전이므로 테스트의 용이성을 위해 CSRF, CORS, HttpBasic의 설정을 비활성화 했습니다
- 토큰의 Claim에 현재 email 데이터를 넣어 사용중이지만 보안 이슈가 발생 할 수 있으므로  id나 다른 데이터로의 변경을 진행해야합니다

# 구성 요소
**PasswordEncoder :**
- 매번 다른 솔팅을 부여하여 암호화하는 BCryptPasswordEncoder를 구현 했으나, Interface로 주입하여 추후 암호화 알고리즘을 변경하더라도 다른 코드에 영향이 최소화 될 수 있는 구성을 채택하였습니다

**MemberPrincipal :**
- UserDetails를 상속받은 사용자 객체의 이름으로 Principal의 네이밍을 채용했습니다 - (principal - spring에서 인증된 사용자를 의미)
- Member를 조회하는 용도로 사용하는 Component에 Service를 붙였으나 도메인 로직과는 거리가 있다고 판단되어 네이밍에 대한 변경을 고려해 볼 수 있을것 같습니다
- ex) MemberPrincipalComponent 등

**JwtTokenGenerator :**
- Secret을 임의의 값을 넣어서 초기화한 상태입니다 추후 외부 주입으로 변경하여 보안성을 높여야 합니다
- Token의 유지 시간을 30분으로 설정했습니다 추후 시간 설정을 외부에서 주입받아 변경 가능성을 열어 둘 수 있을 것 같습니다

**JwtAuthenticationFilter :**
- AUTHORIZATION 헤더에서 토큰을 가져옵니다

## 추가 정보 및 가이드
- Controller Layer에서 유저 정보 사용 시 @AuthenticationPrincipal 어노테이션으로 Member를 바로 사용 가능합니다
```java
@GetMapping("/sample")
    public ResponseDTO<Void> howToGetMember(@AuthenticationPrincipal Member member) {
        //do something....
    }
```
- #27

**Comment by Galmaeki** [comment]
Security 작성 완료했습니다!
어색한부분 지적해주시면 수정하겠습니다!
