### ISSUE TITLE
[Docs] 도커 내부의 로그를 확인한다.

### ISSUE THREAD

**Issue by Galmaeki** [10aeat/10aeat_Backend#47]
# 목적
- 현재 프로젝트의 로깅 전략이 로컬에 파일을 생성하여 작성하는 방식에서 도커를 사용하므로 일반적인 확인은 어렵습니다
- 이에 도커 내부의 로그를 확인하는 명령어들을 기록하여 개발팀 누구든 편하게 로그를 확인할 수 있습니다

## 내용
1. ssh를 이용하여 EC2 인스턴스에 접근
2. 컨테이너 내부의 쉘에 접근
```shell
docker exec -it [컨테이너 명 or 컨테이너 id] [접근 할 쉘의 도커 내부 경로]
```
```shell
docker exec -it my-container /bin/sh
```
3. logs 폴더로 이동
  - 현재 로그는 logs 폴더 내부의 spring-boot-logger.log 파일에 저장됩니다
```shell
cd logs
```
4. 로그 파일 확인
  - 아래의 명령어 외에도 log파일을 확인하는 다양한 명령어가 존재합니다

**전체 파일 확인**
```shell
cat spring-boot-logger.log
```
**페이지 단위로 확인**
```shell
less spring-boot-logger.log
```

**Comment by ghrltjdtprbs** [comment]
확인했습니다! 개발할 때 유용하게 이용할 것 같네요 👍👍

**Comment by asd42270** [comment]
확인했슴다!! 감사합니다~!~!
